### ISSUE TITLE
Odd repeated sync issue

### ISSUE THREAD

**Issue by Dukko** [Taxel/PlexTraktSync#10]
For some reason, when I run the script automatically, it marks as watched a specific special of the show Letterkenny, this one: https://trakt.tv/shows/letterkenny/seasons/0/episodes/20

I currently have 66 plays, all accrued in the last couple of weeks. Obviously I am not this much of a fan of Letterkenny :) 

My logs just say that it keeps marking it as watched on trakt. Any idea?

**Comment by Dukko** [comment]
It has now stopped for that episode. However, it seems to mark as played some episodes as soon as I add them to the server. Still puzzled by this behavior.

**Comment by cowbe0x004** [comment]
I'm also getting duplicate sync for movie "Danger Close".

**Comment by gitthangbaby** [comment]
when i mark movie unwatched in Plex, watch status will bounce back from Trakt. Probably not a common situation, but could be added as a comment similar to "if ratings differ, Trakt takes precedence".

**Comment by flammable** [comment]
I think this is happening for me, too. The script is marking a bunch of stuff, all specials/extras, as 'watched' each time I run a sync. I can produce a list if that'll help.

trakt_cache.sqlite is created the first time the script runs, but on subsequent runs, the file is not modified at all. I don't know if that's expected behavior. I deleted trakt_cache.sqlite, and it was recreated upon running another sync. The script continued to mark the same specials/extras as 'watched' (they now have multiple 'watches' on trakt).

I'm running this script on macOS 10.15.3 with Python 3.8.2. I followed the instructions in the readme, though the only thing I changed was the config.json file - I set `watched_status` to `true`, but set the other items to `false`.

Please let me know if I can provide anything that'd help with tracking this down, if you're willing. Thanks!

**Comment by Vaxter** [comment]
Same issue here.
Usually specials for different shows are always synced again.

Also, another issue, is that ir marks entire unwatched shows watched on both trakt and plex.
For me the other issue got fixed after deleting trakt_cache.sqlite, but specials are still synced.

**Comment by twolaw** [comment]
For duplicate plays on movies, it's because sometimes trakt change movie slug name and the script don't know it because of the cache file. Removing cache file is the fix.
For specials tvshow sync, does it sync a special episode that you have never seen OR sync multiple times a special episode you have already seen one time on plex ?
I may have an idea of the problem.

**Comment by flammable** [comment]
In my case, removing the cache file still causes the script to mark the special as 'watched' again (the cache file is rebuilt). Each time I run the script, it adds additional plays to the item in Trakt.

In every case, it's marked specials as 'watched' in Trakt that I've already watched in Plex.

Thanks for taking a look!

**Comment by twolaw** [comment]
Yes the 2 problems are differents, cache removal is not the solution for specials episodes bug.

The problem of specials as I see it : 
- specials episodes are not fetched from trakt 'watched progress'
- when the script compares plex and trakt watched status, a special watched in plex cannot find its twin in trakt -> the script think trakt needs to be updated

At every sync, it will send to trakt a watched status to specials episodes that has been seen in plex.

I think `pytrakt_extensions.py` need an update.
Maybe try to edit this line :
`data = yield 'shows/{}/progress/watched'.format(show_slug)`
like this
`data = yield 'shows/{}/progress/watched?specials=true'.format(show_slug)`

**Comment by Rouzax** [comment]
I'm seeing the same issue, after the initial sync and doing a second sync the script will set a watched state for episodes I haven't watched.

[last_update.txt](https://github.com/Taxel/PlexTraktSync/files/4564575/last_update.txt)

For instance in this log:
```
2020-04-30 21:09:18,618 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E01
2020-04-30 21:09:19,307 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E02
2020-04-30 21:09:19,779 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E03
2020-04-30 21:09:20,171 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E04
2020-04-30 21:09:20,600 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E05
2020-04-30 21:09:20,940 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E06
2020-04-30 21:09:22,120 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E07
2020-04-30 21:09:52,444 ERROR:JSON decode error: Expecting value: line 1 column 1 (char 0)
2020-04-30 21:09:52,995 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E09
2020-04-30 21:09:53,573 INFO:Show [Briarpatch (2020)]: Marked as watched on trakt: episode S01E10
2020-04-30 21:09:53,573 INFO:Show [Briarpatch (2020)]: Finished sync
```

```
2020-04-30 21:10:08,908 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E01
2020-04-30 21:10:10,043 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E02
2020-04-30 21:10:10,423 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E03
2020-04-30 21:10:10,831 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E04
2020-04-30 21:10:11,231 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E05
2020-04-30 21:10:11,577 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E06
2020-04-30 21:10:12,064 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E07
2020-04-30 21:10:12,757 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E08
2020-04-30 21:10:13,124 INFO:Show [Dispatches from Elsewhere (2020)]: Marked as watched on trakt: episode S01E09
2020-04-30 21:10:13,124 INFO:Show [Dispatches from Elsewhere (2020)]: Finished sync
```

**Comment by Rouzax** [comment]
Just did another sync and this time with debug on, removed the API keys, Bearer and user name.

It synced again `Woezel en Pip` and `Sprookjesboom` as watched right now from Plex to Trakt while I obviously did not watch all those episodes
![image](https://user-images.githubusercontent.com/4103090/80813286-0d3d5780-8bca-11ea-82c1-9411d4b8f12e.png)
[last_update.txt](https://github.com/Taxel/PlexTraktSync/files/4564733/last_update.txt)

**Comment by twolaw** [comment]
Marking watched a not-watched video is not the same issue as marking watched multiple times a video already watched one time. Be more specific.
If your problem is not the same as first post (marking watched multiple times a video already watched one time), you have to open your own issue.

@Rouzax I see many plex GUID 'local' in your log, I think you did not correctly [scrape your Plex content](https://support.plex.tv/articles/200241558-agents/) and matching cannot be perfectly done between plex and trakt.

**Comment by Rouzax** [comment]
@twolaw, Sorry I thought these were similar issues hence me adding the logs here.

I've scraped my data correct as far as I know 😄 
This is how I've setup my TV shows
![image](https://user-images.githubusercontent.com/4103090/80825227-38cb3c80-8be0-11ea-9744-92830b1b3a35.png)

The 2 shows above here are in a Kids Library I don't even want to sync but as far as I see there is now way to exclude libraries.

Briarpatch and Dispatches from Elsewhere (2020) only showed that behaviour once.

You want me to open a new issue?

**Comment by twolaw** [comment]
Open a new issue if you consider it is not the same issue. You don't even say if you have repeated watched status on trakt...

Briarpatch (2020):
Logs are ok. We don't know precisely what is wrong here. Do you own all 10 episodes in Plex ? Which one did you actually watch ? What are watched status on Plex ? How many watched status are on trakt for each ? ...
Same questions for other show. You have to give details and context.

**Comment by Rouzax** [comment]
> 
> 
> Open a new issue if you consider it is not the same issue. You don't even say if you have repeated watched status on trakt...
> 
> Briarpatch (2020):
> Logs are ok. We don't know precisely what is wrong here. Do you own all 10 episodes in Plex ? Which one did you actually watch ? What are watched status on Plex ? How many watched status are on trakt for each ? ...
> Same questions for other show. You have to give details and context.

For Briarpatch
I manually reset all the watch states back to what they need to be, so I can't definitely give all the answers.

I'll open a new issue but since it is 2 different issues I'll separate them and start with the kids shows that each time set watched since that happens all the time.

**Comment by flammable** [comment]
@twolaw Thanks for taking a look at this! The code change in your last reply to me has improved things dramatically. There's still a couple of specials that are synched, but I imagine there's something else going on with those.

Log excerpts:

```
2020-05-03 00:47:21,458 INFO:Show [Mystery Science Theater 3000 (1987)]: Marked as watched on trakt: episode S00E269
2020-05-03 00:47:28,148 INFO:Show [Archer (2009) (2009)]: Marked as watched on trakt: episode S00E03
```

Let me know if opening a separate issue would be the right thing to do, and if any additional details would help. Thanks again, though, I think this has otherwise resolved the issues I was seeing!

**Comment by twolaw** [comment]
@flammable the 2 episodes you describe have no air date in trakt, it is issue #29.
Episodes without air date have problems to get watched status.
To confirm, do you have example of other episodes without airdate but with no sync issue ?

**Comment by flammable** [comment]
Thanks! I suspected that might have been the issue @Rouzax had mentioned. I'm glad it's not another new sync issue. 😄

I think I can fix this on my end by marking both as unwatched in Plex and on Trakt. That'd get me to the point where I can run the sync script on a schedule.

How can I tell if an episode I'm synching has an airdate or not? I don't see anything in `last_update.log` that mentions "airdate".

(if you want to take this discussion to #29, that's OK too)

**Comment by Vaxter** [comment]
Haven't tried to find the issue, but I did found some time to hack up a script to clean up double watches.
This will go through your history and find all episodes with multiple watch actions and delete all of them except for the first one.
Do not expect this to be reflected on Trakt right away, it could take some time for it to reflect.
Do not expect anything fancy or smart, I just find doubles and remove latest entries.

Right now you can define a range to fetch history, default is 60 days.
Behaviour of script could probably (definitively) be improved by fetching wider date range always but just deleting histories within the last n (from param) days.

If someone could improve the code, please do.
Python is not nearly my default language... :)

This is the MR: #30

**Comment by Rouzax** [comment]
> 
> 
> Thanks! I suspected that might have been the issue @Rouzax had mentioned. I'm glad it's not another new sync issue. 😄
> 
> I think I can fix this on my end by marking both as unwatched in Plex and on Trakt. That'd get me to the point where I can run the sync script on a schedule.
> 
> How can I tell if an episode I'm synching has an airdate or not? I don't see anything in `last_update.log` that mentions "airdate".
> 
> (if you want to take this discussion to #29, that's OK too)

Another option I think might be to add aired dates to https://www.thetvdb.com/ as Trakt imports their data from there so it should update the aired date with something. 
Not sure how often to run that import.

**Comment by Vaxter** [comment]
Not really...
When I cleaned my library I have used span of one year, --days=365.
This way it will probably clean more because it will find more duplicates for old things.
I will try to spare some time to add logging and to do this improvement that I have mentioned wher I will by default select span and then user chooses deleting span.

**Comment by twolaw** [comment]
Another example with the movie "Snow White and the 7 Dwarfs":
On 6th May 2020, Trakt renamed its slug name `snow-white-and-the-seven-dwarfs-1937` into `snow-white-and-the-seven-dwarfs-1938` therefore the cache info about it became wrong and multiples watched status are being added to Trakt until cache is removed and recreated.

A solution must be found about it, removing cache file every x days is not a solution.

**Comment by Vaxter** [comment]
I believe that I have fixed repeated sync issue.
At least it works for me.
Looks like script was not fetching specials watched data from Trakt at all, so for it all of the specials were always considered as unwatched.
I have also added modification for history cleaner to consider greater ranges when cleaning up library, and scanning and cleaning range are bot configurable now.
I have added logging which episode plays are removed from history.

Requirements have to updated after pull since I have added a new one.

There is still an issue that marks unwatched shows as watched on Plex, but this is probably, as already mentioned, slug issue.
If I find some time I'll try take a look at it next week.

Everything so far is added in #30

**Comment by twolaw** [comment]
> Looks like script was not fetching specials watched data from Trakt at all, so for it all of the specials were always considered as unwatched.

That's what I said [11 days ago](https://github.com/Taxel/PlexTraktSync/issues/10#issuecomment-621389284), but it is only a part of the solution.
Your cleaning script brings help but does not fix the bug.
Like I said, removing cache file or launching a cleaning script every x days is not a solution.
Besides, some people want to keep logs of their multiple watch of movies along years. So removing all duplicate watches is not always wanted.

**Comment by Vaxter** [comment]
> > Looks like script was not fetching specials watched data from Trakt at all, so for it all of the specials were always considered as unwatched.
> 
> That's what I said [11 days ago](https://github.com/Taxel/PlexTraktSync/issues/10#issuecomment-621389284), but it is only a part of the solution.
> Your cleaning script brings help but does not fix the bug.
> Like I said, removing cache file or launching a cleaning script every x days is not a solution.
> Besides, some people want to keep logs of their multiple watch of movies along years. So removing all duplicate watches is not always wanted.

I did change the behaviour, and now bug should be fixed in the original script.
Take a look at #30 pytrakt_extensions.py line 57.
When shows are fetched I also fetch specials so no duplicates for me.
I have synced entire library without cleaning cache a bunch of times and never got any duplicate.

**Comment by twolaw** [comment]
> now bug should be fixed.

No, there is still missing air date bug and changing slug name bug. Both still create duplicated watched status, and a fix is needed.
In fact, you did not give any bugfix.

**Comment by Vaxter** [comment]
> In fact, you did not give any bugfix.

Ok, if you say so.
If the issue happens to me again I’ll take a look.
So far this works for me.

**Comment by twolaw** [comment]
Here is a solution I wrote : [Fix multiple watched bug](https://github.com/twolaw/PlexTraktSync/commit/09ec0ad627248ef2815771fd15ed7cf287ae8111)
It should fix the 3 problems I've found so far linked to this issue :
- using trakt id instead of slug
- fetching specials episodes status
- fetching episodes even if no air date #29 

If someone want to try and tell me if it works.

**Comment by Rouzax** [comment]
Sure, I'll give it a go.
Let me know what I should do to test (remove cache yes/no, etc)

**Comment by twolaw** [comment]
There is no need to remove cache because it solves this problem.
Only copy `main.py` and `pytrakt_extensions.py` from [this branch](https://github.com/twolaw/PlexTraktSync/tree/multiple-watched-fix) then run a sync.

**Comment by Rouzax** [comment]
Okay, so I first needed to add the Kids TV libary back into Plex.
After doing that all episode were obviously unwatched, then ran the script and pretty much all of them are now marked as watched with the exception of.

- All episodes and seasons of `Ernst, Bobbie en de rest` (which doesn't seem to have a Trakt listing)
- All episodes and seasons of `Freek in het Wild` (which doesn't seem to have a Trakt listing)
- All episodes and seasons of `Freek Tegen De Stropers` (which doesn't seem to have a Trakt listing)

There is 1 episode of `Disney Animated Shorts` in `Season 1938` Episode 6 `Mickey's Trailer` that is still marked unwatched.
[last_update.txt](https://github.com/Taxel/PlexTraktSync/files/4614824/last_update.txt)

Also did a second run and nothing got added to changed ,so it looks a lot better

**Comment by twolaw** [comment]
Ok, very good news!
I will create the Pull Request then.

About content not on trakt, there is nothing we can do about it except maybe add it yourself on thetvdb.com.

**Comment by Rouzax** [comment]
> 
> 
> Ok, very good news!
> I will create the Pull Request then.
> 
> About content not on trakt, there is nothing we can do about it except maybe add it yourself on thetvdb.com.

No, it was just a lonely episode that I apparently did not watch yet so has nothing to do with this script. Sorry for the confussion

**Comment by Rouzax** [comment]
@Vaxter or @twolaw, Would you maybe alos be able to help by creating a script that will remove all entries from Trakt collection from before a certain date?

Going through my Trakt pages I noticed that somehow I have a huge number of collections of absolute garbage Shows and Movies that all seem to be collected on `May 18, 2013 17:29`

Have been removing them one by one at a time but there seems to be thousands

**Comment by Vaxter** [comment]
Sure, if it's all the entries before certain date.
I'll tinker it within the next couple of days, if @twolaw doesn't beat me to it. :)

**Comment by twolaw** [comment]
You can try this [http://www.brendanspijkerman.nl/trakthistorymanager/](http://www.brendanspijkerman.nl/trakthistorymanager/)
I already used it, it's helpful.

**Comment by Rouzax** [comment]
While sharing handy Trakt Tools 😄 
I ran into this one to delete resume point from movies or episodes.
https://github.com/sharkykh/tppm

**Comment by Rouzax** [comment]
> 
> 
> You can try this http://www.brendanspijkerman.nl/trakthistorymanager/
> I already used it, it's helpful.

Unfortunately this only does watched, not collected.

**Comment by Rouzax** [comment]
I used the Kodi Trakt plugin to sync "deleted episodes and movies from Trakt Collection". It removed over 12.000 entries 😄 
Thanks for all your help.

**Comment by flammable** [comment]
@twolaw Hey, just wanted to say thanks! I updated to the latest commit, and everything works great. I appreciate your work on this script!

**Comment by ronilaukkarinen** [comment]
Still having this... makes this unusable for me. It iterates more and more counts, I have over 1000 plays for some movies now. Just checked and  `Your branch is up to date with 'origin/master'.` so the update did not solve the problem.

[![Screenshot](https://i.imgur.com/M4G2VVa.png)

**Comment by twolaw** [comment]
Can you remove trakt_cache.sqlite file, then edit config.json `log_debug_messages` to True, then run a sync.
And tell us if Guns Akimbo plays count increased after the sync.
If so, please show last_update.log content (here or on a zerobin, pastebin,...).
