### ISSUE TITLE
404 Error on Watchlist

### ISSUE THREAD

**Issue by moust4ki** [Taxel/PlexTraktSync#2290]
### Confirmation

- [x] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [x] I have checked if an identical issue or discussion already exists
- [x] I have tried downgrading to find version that can be used as a workaround

### The problem

Hello,

I just have an error blocking PlexTraktSync: When I trigger a sync I have a 404 error.
` NotFound: (404) not_found;                                                                                                                
         https://metadata.provider.plex.tv/library/sections/watchlist/all?includeCollections=0&includeExternalMedia=0&includeUserState=0 <Error    
         error="Not Found" message="Section 'watchlist' not found!" statusCode="404"/>                                                             
Error: Error running sync command: (404) not_found; https://metadata.provider.plex.tv/library/sections/watchlist/all?includeCollections=0&includeExternalMedia=0&includeUserState=0 <Error error="Not Found" message="Section 'watchlist' not found!" statusCode="404"/>`

I think it's since the last update of my Plex server. I have redone the setup of PlexTraktSync with my server but same issue.

### Steps to reproduce the behavior

As soon as I start the sync, it abords with this error.

### Error trace / logs

```text
Plex Media Server Authentication Token and base URL have been added to servers.yml
INFO     Connecting with url: https://XXXXXXXXXXXXXXX.plex.direct:32400, timeout 30 seconds                            
INFO     Sync Movie sections: ['Films', 'Films 4K', 'Autres vidéos']                                                                               
INFO     Sync Show sections: ['Séries TV']                                                                                                         
INFO     Enable sync plugin 'AddCollectionPlugin': True                                                                                            
INFO     Enable sync plugin 'ClearCollectedPlugin': False                                                                                          
INFO     Enable sync plugin 'LikedListsPlugin': True                                                                                               
INFO     Enable sync plugin 'SyncRatingsPlugin': True                                                                                              
INFO     Enable sync plugin 'SyncWatchedPlugin': True                                                                                              
INFO     Enable sync plugin 'TraktListsPlugin': True                                                                                               
INFO     Enable sync plugin 'WatchListPlugin': True                                                                                                
ERROR    (404) not_found;                                                                                                                          
         https://metadata.provider.plex.tv/library/sections/watchlist/all?includeCollections=0&includeExternalMedia=0&includeUserState=0 <Error    
         error="Not Found" message="Section 'watchlist' not found!" statusCode="404"/>                                                             
         ╭────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────╮
         │ /app/plextraktsync/cli.py:28 in wrap                                                                                                   │
         │                                                                                                                                        │
         │    25 │   │   │   cmd = getattr(module, name)                                                                                          │
         │    26 │   │   │                                                                                                                        │
         │    27 │   │   │   try:                                                                                                                 │
         │ ❱  28 │   │   │   │   cmd(*args, **kwargs)                                                                                             │
         │    29 │   │   │   except EOFError as e:                                                                                                │
         │    30 │   │   │   │   raise ClickException(f"Program requested terminal, No terminal is                                                │
         │       connected: {e}")                                                                                                                 │
         │    31 │   │   │   except ClickException as e:                                                                                          │
         │                                                                                                                                        │
         │ /app/plextraktsync/commands/sync.py:74 in sync                                                                                         │
         │                                                                                                                                        │
         │   71 │   │   │   w.print_plan(print=logger.info)                                                                                       │
         │   72 │   │   if dry_run:                                                                                                               │
         │   73 │   │   │   logger.info("Enabled dry-run mode: not making actual changes")                                                        │
         │ ❱ 74 │   │   run_async(runner, walker=w, dry_run=config.dry_run)                                                                       │
         │   75                                                                                                                                   │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/site-packages/decorator.py:235 in fun                                                                        │
         │                                                                                                                                        │
         │   232 │   │   def fun(*args, **kw):                                                                                                    │
         │   233 │   │   │   if not kwsyntax:                                                                                                     │
         │   234 │   │   │   │   args, kw = fix(args, kw, sig)                                                                                    │
         │ ❱ 235 │   │   │   return caller(func, *(extras + args), **kw)                                                                          │
         │   236 │                                                                                                                                │
         │   237 │   fun.__name__ = func.__name__                                                                                                 │
         │   238 │   fun.__doc__ = func.__doc__                                                                                                   │
         │                                                                                                                                        │
         │ /app/plextraktsync/decorators/coro.py:15 in coro                                                                                       │
         │                                                                                                                                        │
         │   12 │                                                                                                                                 │
         │   13 │   https://github.com/pallets/click/issues/85#issuecomment-503464628                                                             │
         │   14 │   """                                                                                                                           │
         │ ❱ 15 │   return asyncio.run(f(*args, **kwargs))                                                                                        │
         │   16                                                                                                                                   │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/asyncio/runners.py:195 in run                                                                                │
         │                                                                                                                                        │
         │   192 │   │   │   "asyncio.run() cannot be called from a running event loop")                                                          │
         │   193 │                                                                                                                                │
         │   194 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                                                               │
         │ ❱ 195 │   │   return runner.run(main)                                                                                                  │
         │   196                                                                                                                                  │
         │   197                                                                                                                                  │
         │   198 def _cancel_all_tasks(loop):                                                                                                     │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/asyncio/runners.py:118 in run                                                                                │
         │                                                                                                                                        │
         │   115 │   │                                                                                                                            │
         │   116 │   │   self._interrupt_count = 0                                                                                                │
         │   117 │   │   try:                                                                                                                     │
         │ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                                                           │
         │   119 │   │   except exceptions.CancelledError:                                                                                        │
         │   120 │   │   │   if self._interrupt_count > 0:                                                                                        │
         │   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                                                       │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/asyncio/base_events.py:725 in run_until_complete                                                             │
         │                                                                                                                                        │
         │    722 │   │   if not future.done():                                                                                                   │
         │    723 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')                                                   │
         │    724 │   │                                                                                                                           │
         │ ❱  725 │   │   return future.result()                                                                                                  │
         │    726 │                                                                                                                               │
         │    727 │   def stop(self):                                                                                                             │
         │    728 │   │   """Stop running the event loop.                                                                                         │
         │                                                                                                                                        │
         │ /app/plextraktsync/commands/sync.py:13 in run_async                                                                                    │
         │                                                                                                                                        │
         │   10                                                                                                                                   │
         │   11 @coro                                                                                                                             │
         │   12 async def run_async(runner, **kwargs):                                                                                            │
         │ ❱ 13 │   await runner.sync(**kwargs)                                                                                                   │
         │   14                                                                                                                                   │
         │   15                                                                                                                                   │
         │   16 def sync(                                                                                                                         │
         │                                                                                                                                        │
         │ /app/plextraktsync/sync/Sync.py:45 in sync                                                                                             │
         │                                                                                                                                        │
         │   42 │   │   self.walker = walker                                                                                                      │
         │   43 │   │   is_partial = walker.is_partial                                                                                            │
         │   44 │   │                                                                                                                             │
         │ ❱ 45 │   │   pm = self.pm                                                                                                              │
         │   46 │   │   pm.hook.init(sync=self, pm=pm, is_partial=is_partial, dry_run=dry_run)                                                    │
         │   47 │   │                                                                                                                             │
         │   48 │   │   if self.config.need_library_walk:                                                                                         │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/functools.py:1026 in __get__                                                                                 │
         │                                                                                                                                        │
         │   1023 │   │   │   raise TypeError(msg) from None                                                                                      │
         │   1024 │   │   val = cache.get(self.attrname, _NOT_FOUND)                                                                              │
         │   1025 │   │   if val is _NOT_FOUND:                                                                                                   │
         │ ❱ 1026 │   │   │   val = self.func(instance)                                                                                           │
         │   1027 │   │   │   try:                                                                                                                │
         │   1028 │   │   │   │   cache[self.attrname] = val                                                                                      │
         │   1029 │   │   │   except TypeError:                                                                                                   │
         │                                                                                                                                        │
         │ /app/plextraktsync/sync/Sync.py:37 in pm                                                                                               │
         │                                                                                                                                        │
         │   34 │   │   from .plugin import SyncPluginManager                                                                                     │
         │   35 │   │                                                                                                                             │
         │   36 │   │   pm = SyncPluginManager()                                                                                                  │
         │ ❱ 37 │   │   pm.register_plugins(self)                                                                                                 │
         │   38 │   │                                                                                                                             │
         │   39 │   │   return pm                                                                                                                 │
         │   40                                                                                                                                   │
         │                                                                                                                                        │
         │ /app/plextraktsync/sync/plugin/SyncPluginManager.py:68 in register_plugins                                                             │
         │                                                                                                                                        │
         │   65 │   │   │   with measure_time(f"Created '{plugin.__name__}' plugin",                                                              │
         │      logger=self.logger.debug):                                                                                                        │
         │   66 │   │   │   │   p = plugin.factory(sync)                                                                                          │
         │   67 │   │   │   with measure_time(f"Registered '{plugin.__name__}' plugin",                                                           │
         │      logger=self.logger.debug):                                                                                                        │
         │ ❱ 68 │   │   │   │   self.pm.register(p)                                                                                               │
         │   69                                                                                                                                   │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/site-packages/apluggy/wrap/main.py:126 in register                                                           │
         │                                                                                                                                        │
         │   123 │   ) -> Union[str, None]:                                                                                                       │
         │   124 │   │   if callable(plugin):                                                                                                     │
         │   125 │   │   │   plugin = plugin()                                                                                                    │
         │ ❱ 126 │   │   return super().register(plugin, name=name)                                                                               │
         │   127 │                                                                                                                                │
         │   128 │   def get_canonical_name(self, plugin: _Plugin) -> str:                                                                        │
         │   129 │   │   '''Override to include class names in plugin names.'''                                                                   │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/site-packages/pluggy/_manager.py:157 in register                                                             │
         │                                                                                                                                        │
         │   154 │   │                                                                                                                            │
         │   155 │   │   # register matching hook implementations of the plugin                                                                   │
         │   156 │   │   for name in dir(plugin):                                                                                                 │
         │ ❱ 157 │   │   │   hookimpl_opts = self.parse_hookimpl_opts(plugin, name)                                                               │
         │   158 │   │   │   if hookimpl_opts is not None:                                                                                        │
         │   159 │   │   │   │   normalize_hookimpl_opts(hookimpl_opts)                                                                           │
         │   160 │   │   │   │   method: _HookImplFunction[object] = getattr(plugin, name)                                                        │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/site-packages/pluggy/_manager.py:184 in parse_hookimpl_opts                                                  │
         │                                                                                                                                        │
         │   181 │   │   customize how hook implementation are picked up. By default, returns the                                                 │
         │   182 │   │   options for items decorated with :class:`HookimplMarker`.                                                                │
         │   183 │   │   """                                                                                                                      │
         │ ❱ 184 │   │   method: object = getattr(plugin, name)                                                                                   │
         │   185 │   │   if not inspect.isroutine(method):                                                                                        │
         │   186 │   │   │   return None                                                                                                          │
         │   187 │   │   try:                                                                                                                     │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/functools.py:1026 in __get__                                                                                 │
         │                                                                                                                                        │
         │   1023 │   │   │   raise TypeError(msg) from None                                                                                      │
         │   1024 │   │   val = cache.get(self.attrname, _NOT_FOUND)                                                                              │
         │   1025 │   │   if val is _NOT_FOUND:                                                                                                   │
         │ ❱ 1026 │   │   │   val = self.func(instance)                                                                                           │
         │   1027 │   │   │   try:                                                                                                                │
         │   1028 │   │   │   │   cache[self.attrname] = val                                                                                      │
         │   1029 │   │   │   except TypeError:                                                                                                   │
         │                                                                                                                                        │
         │ /app/plextraktsync/sync/WatchListPlugin.py:60 in plex_wl                                                                               │
         │                                                                                                                                        │
         │    57 │   def plex_wl(self):                                                                                                           │
         │    58 │   │   from plextraktsync.plex.PlexWatchList import PlexWatchList                                                               │
         │    59 │   │                                                                                                                            │
         │ ❱  60 │   │   return PlexWatchList(self.plex.watchlist())                                                                              │
         │    61 │                                                                                                                                │
         │    62 │   @cached_property                                                                                                             │
         │    63 │   def sync_wl(self):                                                                                                           │
         │                                                                                                                                        │
         │ /app/plextraktsync/plex/PlexApi.py:249 in watchlist                                                                                    │
         │                                                                                                                                        │
         │   246 │   │   │   "includeUserState": 0,                                                                                               │
         │   247 │   │   }                                                                                                                        │
         │   248 │   │   try:                                                                                                                     │
         │ ❱ 249 │   │   │   return self.account.watchlist(libtype=libtype, **params)                                                             │
         │   250 │   │   except BadRequest as e:                                                                                                  │
         │   251 │   │   │   self.logger.error(f"Error during {self.account.username} watchlist access:                                           │
         │       {e}")                                                                                                                            │
         │   252 │   │   │   return None                                                                                                          │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/site-packages/plexapi/myplex.py:953 in watchlist                                                             │
         │                                                                                                                                        │
         │    950 │   │   params.update(kwargs)                                                                                                   │
         │    951 │   │                                                                                                                           │
         │    952 │   │   key =                                                                                                                   │
         │        f'{self.METADATA}/library/sections/watchlist/{filter}{utils.joinArgs(params)}'                                                  │
         │ ❱  953 │   │   return self._toOnlineMetadata(self.fetchItems(key, maxresults=maxresults),                                              │
         │        **kwargs)                                                                                                                       │
         │    954 │                                                                                                                               │
         │    955 │   def onWatchlist(self, item):                                                                                                │
         │    956 │   │   """ Returns True if the item is on the user's watchlist.                                                                │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/site-packages/plexapi/base.py:316 in fetchItems                                                              │
         │                                                                                                                                        │
         │    313 │   │   │   headers['X-Plex-Container-Start'] = str(container_start)                                                            │
         │    314 │   │   │   headers['X-Plex-Container-Size'] = str(container_size)                                                              │
         │    315 │   │   │                                                                                                                       │
         │ ❱  316 │   │   │   data = self._server.query(ekey, headers=headers, params=params)                                                     │
         │    317 │   │   │   subresults = self.findItems(data, cls, ekey, **kwargs)                                                              │
         │    318 │   │   │   total_size = utils.cast(int, data.attrib.get('totalSize') or                                                        │
         │        data.attrib.get('size')) or len(subresults)                                                                                     │
         │    319                                                                                                                                 │
         │                                                                                                                                        │
         │ /usr/local/lib/python3.13/site-packages/plexapi/myplex.py:251 in query                                                                 │
         │                                                                                                                                        │
         │    248 │   │   │   │   │   raise TwoFactorRequired(message)                                                                            │
         │    249 │   │   │   │   raise Unauthorized(message)                                                                                     │
         │    250 │   │   │   elif response.status_code == 404:                                                                                   │
         │ ❱  251 │   │   │   │   raise NotFound(message)                                                                                         │
         │    252 │   │   │   elif response.status_code == 422 and "Invalid token" in response.text:                                              │
         │    253 │   │   │   │   raise Unauthorized(message)                                                                                     │
         │    254 │   │   │   else:                                                                                                               │
         ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
         NotFound: (404) not_found;                                                                                                                
         https://metadata.provider.plex.tv/library/sections/watchlist/all?includeCollections=0&includeExternalMedia=0&includeUserState=0 <Error    
         error="Not Found" message="Section 'watchlist' not found!" statusCode="404"/>                                                             
Error: Error running sync command: (404) not_found; https://metadata.provider.plex.tv/library/sections/watchlist/all?includeCollections=0&includeExternalMedia=0&includeUserState=0 <Error error="Not Found" message="Section 'watchlist' not found!" statusCode="404"/>
```

### Expected behavior

Sync without error

### Inspect of problematic items

```text

```

### Config file contents

```yaml

```

### Install method

Unraid installation (not supported)

### Version

0.34.12

### Python Version

3.13.5

### Plex Server Version

4.17.0

### Operating System and Version

Unraid

**Comment by xairoo** [comment]
Same. It appeared with the update from plexmediaserver_1.41.9.9961 to plexmediaserver_1.42.1.10060.

And from plextraktsync 0.34.11 to 0.34.12 (downgrade to 0.34.11 didn't helped).

**Comment by Varming73** [comment]
Got the exact same error on Plex 1.42.1.10060

**Comment by bastardsheep** [comment]
Is there a way to get it to sync everything else? All I'm trying to do is get my trakt watched and unwatched marks in to Plex. I don't care about rankings, watchlist, or anything else.

**Comment by simonc56** [comment]
Plex updated its API urls.

The fix is on the way : 
- https://github.com/pushingkarmaorg/python-plexapi/pull/1542

**Comment by hobeone** [comment]
@bastardsheep if you can't wait for the fix this should exclude watchlists from the sync.  Edit your servers.yml file and add this section to your server config:

```
    config:
      sync:
        plex_to_trakt:
          watchlist: false
        trakt_to_plex:
          watchlist: false
```

**Comment by keldian** [comment]
For me, turning off watchlist sync allowed it to run without errors, but it didn't sync new plays.

**Comment by ctejada10** [comment]
Just hopping on to say that [this comment](https://github.com/Taxel/PlexTraktSync/issues/2290#issuecomment-3191664425) worked for me. Everything else worked and no slowdowns that I can notice

**Comment by raaphhh** [comment]
Following because I got the same issue

**Comment by simonc56** [comment]
Fixed in version `0.34.13`

**Comment by ctejada10** [comment]
Sorry to comment on a closed issue, but has anybody been able to test? I am still getting the same error, just wanna make sure I'm not doing something dumb in my setup.

Thank you for the push, though!

**Comment by ctejada10** [comment]
> > Sorry to comment on a closed issue, but has anybody been able to test? I am still getting the same error, just wanna make sure I'm not doing something dumb in my setup.
> > Thank you for the push, though!
> 
> I updated using `plextraktsync self-update`, modified the config file so it had "trakt_to_plex" "watchlist: true", then ran a sync. Worked perfectly, no errors, my watchlist now mirrors what is in Trakt.

Hmm, all right. I'm running it via Docker; maybe it's not pushed there yet?

**Comment by ctejada10** [comment]
Yep! It was on me, my Docker container was not running the latest version. Sorry about that!
